# Generated by Django 2.1.5 on 2019-01-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('handle', models.CharField(max_length=64, verbose_name='Name / Handle')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='People attending, including yourself')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hide name from listing')),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('handle', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
