# Generated by Django 2.1.5 on 2019-01-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddt', '0002_auto_20190128_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open', models.BooleanField(default=False)),
                ('wall_open', models.BooleanField(default=False)),
            ],
        ),
    ]
