# Generated by Django 2.1.5 on 2019-01-28 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddt', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='People attending, including yourself'),
        ),
    ]
